export type PaisTelefone = {
  iso: string;
  nome: string;
  dial: string;
  bandeira: string;
};

export function bandeiraPais(iso: string): string {
  return iso
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)));
}

export const PAISES_TELEFONE: PaisTelefone[] = [
  { iso: "AF", nome: "Afeganistão", dial: "+93", bandeira: "🇦🇫" },
  { iso: "AL", nome: "Albânia", dial: "+355", bandeira: "🇦🇱" },
  { iso: "DE", nome: "Alemanha", dial: "+49", bandeira: "🇩🇪" },
  { iso: "AD", nome: "Andorra", dial: "+376", bandeira: "🇦🇩" },
  { iso: "AO", nome: "Angola", dial: "+244", bandeira: "🇦🇴" },
  { iso: "AG", nome: "Antígua e Barbuda", dial: "+1268", bandeira: "🇦🇬" },
  { iso: "SA", nome: "Arábia Saudita", dial: "+966", bandeira: "🇸🇦" },
  { iso: "DZ", nome: "Argélia", dial: "+213", bandeira: "🇩🇿" },
  { iso: "AR", nome: "Argentina", dial: "+54", bandeira: "🇦🇷" },
  { iso: "AM", nome: "Armênia", dial: "+374", bandeira: "🇦🇲" },
  { iso: "AU", nome: "Austrália", dial: "+61", bandeira: "🇦🇺" },
  { iso: "AT", nome: "Áustria", dial: "+43", bandeira: "🇦🇹" },
  { iso: "AZ", nome: "Azerbaijão", dial: "+994", bandeira: "🇦🇿" },
  { iso: "BS", nome: "Bahamas", dial: "+1242", bandeira: "🇧🇸" },
  { iso: "BH", nome: "Bahrein", dial: "+973", bandeira: "🇧🇭" },
  { iso: "BD", nome: "Bangladesh", dial: "+880", bandeira: "🇧🇩" },
  { iso: "BB", nome: "Barbados", dial: "+1246", bandeira: "🇧🇧" },
  { iso: "BE", nome: "Bélgica", dial: "+32", bandeira: "🇧🇪" },
  { iso: "BZ", nome: "Belize", dial: "+501", bandeira: "🇧🇿" },
  { iso: "BJ", nome: "Benin", dial: "+229", bandeira: "🇧🇯" },
  { iso: "BY", nome: "Bielorrússia", dial: "+375", bandeira: "🇧🇾" },
  { iso: "BO", nome: "Bolívia", dial: "+591", bandeira: "🇧🇴" },
  { iso: "BA", nome: "Bósnia e Herzegovina", dial: "+387", bandeira: "🇧🇦" },
  { iso: "BW", nome: "Botsuana", dial: "+267", bandeira: "🇧🇼" },
  { iso: "BR", nome: "Brasil", dial: "+55", bandeira: "🇧🇷" },
  { iso: "BN", nome: "Brunei", dial: "+673", bandeira: "🇧🇳" },
  { iso: "BG", nome: "Bulgária", dial: "+359", bandeira: "🇧🇬" },
  { iso: "BF", nome: "Burkina Faso", dial: "+226", bandeira: "🇧🇫" },
  { iso: "BI", nome: "Burundi", dial: "+257", bandeira: "🇧🇮" },
  { iso: "BT", nome: "Butão", dial: "+975", bandeira: "🇧🇹" },
  { iso: "CV", nome: "Cabo Verde", dial: "+238", bandeira: "🇨🇻" },
  { iso: "CM", nome: "Camarões", dial: "+237", bandeira: "🇨🇲" },
  { iso: "KH", nome: "Camboja", dial: "+855", bandeira: "🇰🇭" },
  { iso: "CA", nome: "Canadá", dial: "+1", bandeira: "🇨🇦" },
  { iso: "QA", nome: "Catar", dial: "+974", bandeira: "🇶🇦" },
  { iso: "KZ", nome: "Cazaquistão", dial: "+7", bandeira: "🇰🇿" },
  { iso: "TD", nome: "Chade", dial: "+235", bandeira: "🇹🇩" },
  { iso: "CL", nome: "Chile", dial: "+56", bandeira: "🇨🇱" },
  { iso: "CN", nome: "China", dial: "+86", bandeira: "🇨🇳" },
  { iso: "CY", nome: "Chipre", dial: "+357", bandeira: "🇨🇾" },
  { iso: "CO", nome: "Colômbia", dial: "+57", bandeira: "🇨🇴" },
  { iso: "KM", nome: "Comores", dial: "+269", bandeira: "🇰🇲" },
  { iso: "CG", nome: "Congo", dial: "+242", bandeira: "🇨🇬" },
  { iso: "CD", nome: "Congo (RDC)", dial: "+243", bandeira: "🇨🇩" },
  { iso: "KP", nome: "Coreia do Norte", dial: "+850", bandeira: "🇰🇵" },
  { iso: "KR", nome: "Coreia do Sul", dial: "+82", bandeira: "🇰🇷" },
  { iso: "CI", nome: "Costa do Marfim", dial: "+225", bandeira: "🇨🇮" },
  { iso: "CR", nome: "Costa Rica", dial: "+506", bandeira: "🇨🇷" },
  { iso: "HR", nome: "Croácia", dial: "+385", bandeira: "🇭🇷" },
  { iso: "CU", nome: "Cuba", dial: "+53", bandeira: "🇨🇺" },
  { iso: "DK", nome: "Dinamarca", dial: "+45", bandeira: "🇩🇰" },
  { iso: "DJ", nome: "Djibuti", dial: "+253", bandeira: "🇩🇯" },
  { iso: "DM", nome: "Dominica", dial: "+1767", bandeira: "🇩🇲" },
  { iso: "EG", nome: "Egito", dial: "+20", bandeira: "🇪🇬" },
  { iso: "SV", nome: "El Salvador", dial: "+503", bandeira: "🇸🇻" },
  { iso: "AE", nome: "Emirados Árabes Unidos", dial: "+971", bandeira: "🇦🇪" },
  { iso: "EC", nome: "Equador", dial: "+593", bandeira: "🇪🇨" },
  { iso: "ER", nome: "Eritreia", dial: "+291", bandeira: "🇪🇷" },
  { iso: "SK", nome: "Eslováquia", dial: "+421", bandeira: "🇸🇰" },
  { iso: "SI", nome: "Eslovênia", dial: "+386", bandeira: "🇸🇮" },
  { iso: "ES", nome: "Espanha", dial: "+34", bandeira: "🇪🇸" },
  { iso: "US", nome: "Estados Unidos", dial: "+1", bandeira: "🇺🇸" },
  { iso: "EE", nome: "Estônia", dial: "+372", bandeira: "🇪🇪" },
  { iso: "SZ", nome: "Eswatini", dial: "+268", bandeira: "🇸🇿" },
  { iso: "ET", nome: "Etiópia", dial: "+251", bandeira: "🇪🇹" },
  { iso: "FJ", nome: "Fiji", dial: "+679", bandeira: "🇫🇯" },
  { iso: "PH", nome: "Filipinas", dial: "+63", bandeira: "🇵🇭" },
  { iso: "FI", nome: "Finlândia", dial: "+358", bandeira: "🇫🇮" },
  { iso: "FR", nome: "França", dial: "+33", bandeira: "🇫🇷" },
  { iso: "GA", nome: "Gabão", dial: "+241", bandeira: "🇬🇦" },
  { iso: "GM", nome: "Gâmbia", dial: "+220", bandeira: "🇬🇲" },
  { iso: "GH", nome: "Gana", dial: "+233", bandeira: "🇬🇭" },
  { iso: "GE", nome: "Geórgia", dial: "+995", bandeira: "🇬🇪" },
  { iso: "GI", nome: "Gibraltar", dial: "+350", bandeira: "🇬🇮" },
  { iso: "GD", nome: "Granada", dial: "+1473", bandeira: "🇬🇩" },
  { iso: "GR", nome: "Grécia", dial: "+30", bandeira: "🇬🇷" },
  { iso: "GL", nome: "Groenlândia", dial: "+299", bandeira: "🇬🇱" },
  { iso: "GT", nome: "Guatemala", dial: "+502", bandeira: "🇬🇹" },
  { iso: "GY", nome: "Guiana", dial: "+592", bandeira: "🇬🇾" },
  { iso: "GN", nome: "Guiné", dial: "+224", bandeira: "🇬🇳" },
  { iso: "GQ", nome: "Guiné Equatorial", dial: "+240", bandeira: "🇬🇶" },
  { iso: "GW", nome: "Guiné-Bissau", dial: "+245", bandeira: "🇬🇼" },
  { iso: "HT", nome: "Haiti", dial: "+509", bandeira: "🇭🇹" },
  { iso: "HN", nome: "Honduras", dial: "+504", bandeira: "🇭🇳" },
  { iso: "HK", nome: "Hong Kong", dial: "+852", bandeira: "🇭🇰" },
  { iso: "HU", nome: "Hungria", dial: "+36", bandeira: "🇭🇺" },
  { iso: "YE", nome: "Iêmen", dial: "+967", bandeira: "🇾🇪" },
  { iso: "FO", nome: "Ilhas Faroé", dial: "+298", bandeira: "🇫🇴" },
  { iso: "MH", nome: "Ilhas Marshall", dial: "+692", bandeira: "🇲🇭" },
  { iso: "SB", nome: "Ilhas Salomão", dial: "+677", bandeira: "🇸🇧" },
  { iso: "IN", nome: "Índia", dial: "+91", bandeira: "🇮🇳" },
  { iso: "ID", nome: "Indonésia", dial: "+62", bandeira: "🇮🇩" },
  { iso: "IR", nome: "Irã", dial: "+98", bandeira: "🇮🇷" },
  { iso: "IQ", nome: "Iraque", dial: "+964", bandeira: "🇮🇶" },
  { iso: "IE", nome: "Irlanda", dial: "+353", bandeira: "🇮🇪" },
  { iso: "IS", nome: "Islândia", dial: "+354", bandeira: "🇮🇸" },
  { iso: "IL", nome: "Israel", dial: "+972", bandeira: "🇮🇱" },
  { iso: "IT", nome: "Itália", dial: "+39", bandeira: "🇮🇹" },
  { iso: "JM", nome: "Jamaica", dial: "+1876", bandeira: "🇯🇲" },
  { iso: "JP", nome: "Japão", dial: "+81", bandeira: "🇯🇵" },
  { iso: "JO", nome: "Jordânia", dial: "+962", bandeira: "🇯🇴" },
  { iso: "XK", nome: "Kosovo", dial: "+383", bandeira: "🇽🇰" },
  { iso: "KW", nome: "Kuwait", dial: "+965", bandeira: "🇰🇼" },
  { iso: "LA", nome: "Laos", dial: "+856", bandeira: "🇱🇦" },
  { iso: "LS", nome: "Lesoto", dial: "+266", bandeira: "🇱🇸" },
  { iso: "LV", nome: "Letônia", dial: "+371", bandeira: "🇱🇻" },
  { iso: "LB", nome: "Líbano", dial: "+961", bandeira: "🇱🇧" },
  { iso: "LR", nome: "Libéria", dial: "+231", bandeira: "🇱🇷" },
  { iso: "LY", nome: "Líbia", dial: "+218", bandeira: "🇱🇾" },
  { iso: "LI", nome: "Liechtenstein", dial: "+423", bandeira: "🇱🇮" },
  { iso: "LT", nome: "Lituania", dial: "+370", bandeira: "🇱🇹" },
  { iso: "LU", nome: "Luxemburgo", dial: "+352", bandeira: "🇱🇺" },
  { iso: "MO", nome: "Macau", dial: "+853", bandeira: "🇲🇴" },
  { iso: "MK", nome: "Macedônia do Norte", dial: "+389", bandeira: "🇲🇰" },
  { iso: "MG", nome: "Madagascar", dial: "+261", bandeira: "🇲🇬" },
  { iso: "MY", nome: "Malásia", dial: "+60", bandeira: "🇲🇾" },
  { iso: "MW", nome: "Malawi", dial: "+265", bandeira: "🇲🇼" },
  { iso: "MV", nome: "Maldivas", dial: "+960", bandeira: "🇲🇻" },
  { iso: "ML", nome: "Mali", dial: "+223", bandeira: "🇲🇱" },
  { iso: "MT", nome: "Malta", dial: "+356", bandeira: "🇲🇹" },
  { iso: "MA", nome: "Marrocos", dial: "+212", bandeira: "🇲🇦" },
  { iso: "MU", nome: "Maurício", dial: "+230", bandeira: "🇲🇺" },
  { iso: "MR", nome: "Mauritânia", dial: "+222", bandeira: "🇲🇷" },
  { iso: "MX", nome: "México", dial: "+52", bandeira: "🇲🇽" },
  { iso: "MM", nome: "Mianmar", dial: "+95", bandeira: "🇲🇲" },
  { iso: "FM", nome: "Micronésia", dial: "+691", bandeira: "🇫🇲" },
  { iso: "MZ", nome: "Moçambique", dial: "+258", bandeira: "🇲🇿" },
  { iso: "MD", nome: "Moldávia", dial: "+373", bandeira: "🇲🇩" },
  { iso: "MC", nome: "Mônaco", dial: "+377", bandeira: "🇲🇨" },
  { iso: "MN", nome: "Mongólia", dial: "+976", bandeira: "🇲🇳" },
  { iso: "ME", nome: "Montenegro", dial: "+382", bandeira: "🇲🇪" },
  { iso: "NA", nome: "Namíbia", dial: "+264", bandeira: "🇳🇦" },
  { iso: "NR", nome: "Nauru", dial: "+674", bandeira: "🇳🇷" },
  { iso: "NP", nome: "Nepal", dial: "+977", bandeira: "🇳🇵" },
  { iso: "NI", nome: "Nicarágua", dial: "+505", bandeira: "🇳🇮" },
  { iso: "NE", nome: "Níger", dial: "+227", bandeira: "🇳🇪" },
  { iso: "NG", nome: "Nigéria", dial: "+234", bandeira: "🇳🇬" },
  { iso: "NO", nome: "Noruega", dial: "+47", bandeira: "🇳🇴" },
  { iso: "NZ", nome: "Nova Zelândia", dial: "+64", bandeira: "🇳🇿" },
  { iso: "OM", nome: "Omã", dial: "+968", bandeira: "🇴🇲" },
  { iso: "NL", nome: "Países Baixos", dial: "+31", bandeira: "🇳🇱" },
  { iso: "PW", nome: "Palau", dial: "+680", bandeira: "🇵🇼" },
  { iso: "PS", nome: "Palestina", dial: "+970", bandeira: "🇵🇸" },
  { iso: "PA", nome: "Panamá", dial: "+507", bandeira: "🇵🇦" },
  { iso: "PG", nome: "Papua-Nova Guiné", dial: "+675", bandeira: "🇵🇬" },
  { iso: "PK", nome: "Paquistão", dial: "+92", bandeira: "🇵🇰" },
  { iso: "PY", nome: "Paraguai", dial: "+595", bandeira: "🇵🇾" },
  { iso: "PE", nome: "Peru", dial: "+51", bandeira: "🇵🇪" },
  { iso: "PL", nome: "Polônia", dial: "+48", bandeira: "🇵🇱" },
  { iso: "PR", nome: "Porto Rico", dial: "+1787", bandeira: "🇵🇷" },
  { iso: "PT", nome: "Portugal", dial: "+351", bandeira: "🇵🇹" },
  { iso: "KE", nome: "Quênia", dial: "+254", bandeira: "🇰🇪" },
  { iso: "KG", nome: "Quirguistão", dial: "+996", bandeira: "🇰🇬" },
  { iso: "GB", nome: "Reino Unido", dial: "+44", bandeira: "🇬🇧" },
  { iso: "CF", nome: "República Centro-Africana", dial: "+236", bandeira: "🇨🇫" },
  { iso: "DO", nome: "República Dominicana", dial: "+1809", bandeira: "🇩🇴" },
  { iso: "CZ", nome: "República Tcheca", dial: "+420", bandeira: "🇨🇿" },
  { iso: "RO", nome: "Romênia", dial: "+40", bandeira: "🇷🇴" },
  { iso: "RW", nome: "Ruanda", dial: "+250", bandeira: "🇷🇼" },
  { iso: "RU", nome: "Rússia", dial: "+7", bandeira: "🇷🇺" },
  { iso: "WS", nome: "Samoa", dial: "+685", bandeira: "🇼🇸" },
  { iso: "SM", nome: "San Marino", dial: "+378", bandeira: "🇸🇲" },
  { iso: "LC", nome: "Santa Lúcia", dial: "+1758", bandeira: "🇱🇨" },
  { iso: "KN", nome: "São Cristóvão e Nevis", dial: "+1869", bandeira: "🇰🇳" },
  { iso: "ST", nome: "São Tomé e Príncipe", dial: "+239", bandeira: "🇸🇹" },
  { iso: "VC", nome: "São Vicente e Granadinas", dial: "+1784", bandeira: "🇻🇨" },
  { iso: "SN", nome: "Senegal", dial: "+221", bandeira: "🇸🇳" },
  { iso: "SL", nome: "Serra Leoa", dial: "+232", bandeira: "🇸🇱" },
  { iso: "RS", nome: "Sérvia", dial: "+381", bandeira: "🇷🇸" },
  { iso: "SC", nome: "Seychelles", dial: "+248", bandeira: "🇸🇨" },
  { iso: "SG", nome: "Singapura", dial: "+65", bandeira: "🇸🇬" },
  { iso: "SY", nome: "Síria", dial: "+963", bandeira: "🇸🇾" },
  { iso: "SO", nome: "Somália", dial: "+252", bandeira: "🇸🇴" },
  { iso: "LK", nome: "Sri Lanka", dial: "+94", bandeira: "🇱🇰" },
  { iso: "SD", nome: "Sudão", dial: "+249", bandeira: "🇸🇩" },
  { iso: "SS", nome: "Sudão do Sul", dial: "+211", bandeira: "🇸🇸" },
  { iso: "SE", nome: "Suécia", dial: "+46", bandeira: "🇸🇪" },
  { iso: "CH", nome: "Suíça", dial: "+41", bandeira: "🇨🇭" },
  { iso: "SR", nome: "Suriname", dial: "+597", bandeira: "🇸🇷" },
  { iso: "TH", nome: "Tailândia", dial: "+66", bandeira: "🇹🇭" },
  { iso: "TW", nome: "Taiwan", dial: "+886", bandeira: "🇹🇼" },
  { iso: "TJ", nome: "Tajiquistão", dial: "+992", bandeira: "🇹🇯" },
  { iso: "TZ", nome: "Tanzânia", dial: "+255", bandeira: "🇹🇿" },
  { iso: "TL", nome: "Timor-Leste", dial: "+670", bandeira: "🇹🇱" },
  { iso: "TG", nome: "Togo", dial: "+228", bandeira: "🇹🇬" },
  { iso: "TO", nome: "Tonga", dial: "+676", bandeira: "🇹🇴" },
  { iso: "TT", nome: "Trinidad e Tobago", dial: "+1868", bandeira: "🇹🇹" },
  { iso: "TN", nome: "Tunísia", dial: "+216", bandeira: "🇹🇳" },
  { iso: "TM", nome: "Turcomenistão", dial: "+993", bandeira: "🇹🇲" },
  { iso: "TR", nome: "Turquia", dial: "+90", bandeira: "🇹🇷" },
  { iso: "TV", nome: "Tuvalu", dial: "+688", bandeira: "🇹🇻" },
  { iso: "UA", nome: "Ucrânia", dial: "+380", bandeira: "🇺🇦" },
  { iso: "UG", nome: "Uganda", dial: "+256", bandeira: "🇺🇬" },
  { iso: "UY", nome: "Uruguai", dial: "+598", bandeira: "🇺🇾" },
  { iso: "UZ", nome: "Uzbequistão", dial: "+998", bandeira: "🇺🇿" },
  { iso: "VU", nome: "Vanuatu", dial: "+678", bandeira: "🇻🇺" },
  { iso: "VA", nome: "Vaticano", dial: "+379", bandeira: "🇻🇦" },
  { iso: "VE", nome: "Venezuela", dial: "+58", bandeira: "🇻🇪" },
  { iso: "VN", nome: "Vietnã", dial: "+84", bandeira: "🇻🇳" },
  { iso: "ZM", nome: "Zâmbia", dial: "+260", bandeira: "🇿🇲" },
  { iso: "ZW", nome: "Zimbábue", dial: "+263", bandeira: "🇿🇼" },
];

export function paisPorIso(iso: string): PaisTelefone | undefined {
  return PAISES_TELEFONE.find((p) => p.iso === iso);
}

export function paisPorDial(dial: string): PaisTelefone | undefined {
  return PAISES_TELEFONE.find((p) => p.dial === dial);
}
